release/0.0.22
## [0.0.22] - 2024-10-04
### Improved
- `all_modules` functionalities:
  - Removes unused functions.
  - Changes DOCLI_DEBUG call.
  - Changes bash set options and set them dynamically.
- RESETs all modules but .devops/version to version 0.0.01 so they can follow the same standards.

diff --git a/.devops/bin/docli b/.devops/bin/docli
--- a/.devops/bin/docli
+++ b/.devops/bin/docli
@@ -1,12 +1,13 @@
 #!/usr/bin/env bash
-set -euo pipefail
+[[ ${DOCLI_DEBUG:-false} == true ]]       && set -exo pipefail || set -eo pipefail
+[[ ${DOCLI_UNSET_VARS:-false} == true ]]  && set -u
 ############################################################################### #dltbr
 #              https://DevOps.click - DevOps taken seriously                  # #dltbr
 ###############################################################################
 #                                   docli
 ###############################################################################
 
-docli_version="0.0.07"
+docli_version="0.0.01"
 docli_file_name="$(basename "$0")"
 docli_file_name_upper="$(basename "$0" | tr '[:lower:]' '[:upper:]')"
 docli_script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
@@ -17,6 +18,9 @@ DOCLI_MODULE=docli
 DOCLI_MODULE_TYPE=bin
 DOCLI_MODULE_VERSION="$docli_version"
 DOCLI_MODULE_UPPER=$(echo "$DOCLI_MODULE" | tr '[:lower:]' '[:upper:]')
+
+## DEBUG INFORMATION
+[[ ${DOCLI_DEBUG:-false} == true ]] && echo -e "\n***** $DOCLI_MODULE version $DOCLI_MODULE_VERSION ($DOCLI_MODULE_TYPE) *****\n"
 
 DOCLI_REMOTE_REPOSITORY_INSTALL_URL="https://raw.githubusercontent.com/devops-click/docli/main/install.sh"
 
@@ -225,7 +229,7 @@ parse_arguments() {
         # args+=("$1")
         # args+=("${1:-}")
         args+=("${current_arg}")
-        eval $DOCLI_DEBUG && echo "++ args+=$args"
+        [[ ${DOCLI_DEBUG:-false} == true ]] && echo "++ args+=$args"
         # remaining_args+=("$current_arg")
         shift
         # return 0
@@ -244,7 +248,7 @@ parse_arguments() {
 }
 
 load_vars
-eval $DOCLI_DEBUG && echo "==> .docli -> load_vars"
+[[ ${DOCLI_DEBUG:-false} == true ]] && echo "==> .docli -> load_vars"
 
 eval $DOCLI_VERBOSE && echo -e "\n**** Running $docli_file_name_upper script ****"
 
@@ -252,8 +256,8 @@ eval $DOCLI_VERBOSE && echo -e "\n**** Running $docli_file_name_upper script ***
 if [[ "$0" = "bash" ]] || [[ "$0" = "/bin/bash" ]] || [[ "$0" = "/bin/sh" ]] || [[ "$0" = "sh" ]] || [[ "$0" = "/bin/zsh" ]] || [[ "$0" = "zsh" ]]; then
   install_local="false" # used when running from a forked repository
 else
-  eval $DOCLI_DEBUG && echo -e "\n******************** INFO: docli installation sourced LOCALLY (DEVELOPER MODE) ********************"
-  eval $DOCLI_DEBUG && echo -e "\n** LOCAL RUN INFO: If DOCLI_REPOSITORY variable is set, we will get files locally from there! (Developers only)\n"
+  [[ ${DOCLI_DEBUG:-false} == true ]] && echo -e "\n******************** INFO: docli installation sourced LOCALLY (DEVELOPER MODE) ********************"
+  [[ ${DOCLI_DEBUG:-false} == true ]] && echo -e "\n** LOCAL RUN INFO: If DOCLI_REPOSITORY variable is set, we will get files locally from there! (Developers only)\n"
   install_local="true" # used when running from a forked repository
 fi
 
@@ -277,12 +281,12 @@ if (( args_silent )); then
   echo "Running in SILENT mode."
 fi
 
-eval $DOCLI_DEBUG && echo "+++++++++++++++++++"
-eval $DOCLI_DEBUG && echo "++ Entered docli ++"
-eval $DOCLI_DEBUG && echo "+++++++++++++++++++"
+[[ ${DOCLI_DEBUG:-false} == true ]] && echo "+++++++++++++++++++"
+[[ ${DOCLI_DEBUG:-false} == true ]] && echo "++ Entered docli ++"
+[[ ${DOCLI_DEBUG:-false} == true ]] && echo "+++++++++++++++++++"
 
-eval $DOCLI_DEBUG && echo "++> docli_command=$docli_command"
-eval $DOCLI_DEBUG && echo "++> docli_option=$docli_option"
+[[ ${DOCLI_DEBUG:-false} == true ]] && echo "++> docli_command=$docli_command"
+[[ ${DOCLI_DEBUG:-false} == true ]] && echo "++> docli_option=$docli_option"
 
 eval $DOCLI_VERBOSE && echo "==> docli -> source .docli"
 source $DOCLI/.docli
@@ -292,7 +296,7 @@ eval $DOCLI_VERBOSE && echo "args_help=${args_help:-}"
 
 # Check docli_eks_assign existence before set.
 : "${docli_eks_assign:=false}"
-eval $DOCLI_DEBUG && echo "++> docli_eks_assign=$docli_eks_assign"
+[[ ${DOCLI_DEBUG:-false} == true ]] && echo "++> docli_eks_assign=$docli_eks_assign"
 
 # parse_arguments "$@"
 ## docli Markdown Generation:
@@ -403,11 +407,11 @@ main() {
         if [ "${1:-}" == "" ]; then
           packer_print_usage
         elif [[ $docli_option == "build" ]]; then
-          eval $DOCLI_DEBUG && echo "++> options -> packer -> build"
+          [[ ${DOCLI_DEBUG:-false} == true ]] && echo "++> options -> packer -> build"
           run_packer_main "$@"
           return 0
         elif [[ -z $docli_option ]]; then
-          eval $DOCLI_DEBUG && echo "++> options -> sso -> ERROR(exception)"
+          [[ ${DOCLI_DEBUG:-false} == true ]] && echo "++> options -> sso -> ERROR(exception)"
           echo "** SSO ERROR: No options provided **"
           sso_print_usage
           exit 1
@@ -470,25 +474,25 @@ main() {
         if [ "${1:-}" == "" ]; then
           sso_print_usage
         elif [[ $docli_option == "clean" ]]; then
-          eval $DOCLI_DEBUG && echo "++> options -> sso -> clean"
+          [[ ${DOCLI_DEBUG:-false} == true ]] && echo "++> options -> sso -> clean"
           sso_clean
           return 0
         elif [[ $sso_eks_assign == "true" ]] ; then
-          eval $DOCLI_DEBUG && echo "++> options -> sso -> sso_eks_assign=true"
+          [[ ${DOCLI_DEBUG:-false} == true ]] && echo "++> options -> sso -> sso_eks_assign=true"
           sso $docli_option
           return 0
         elif [[ $sso_eks_assign == "false" ]] ; then
-          eval $DOCLI_DEBUG && echo "++> options -> sso -> sso_eks_assign=false"
+          [[ ${DOCLI_DEBUG:-false} == true ]] && echo "++> options -> sso -> sso_eks_assign=false"
           sso $docli_option
           return 0
         elif [[ $docli_option == "mfa" ]]; then
-          eval $DOCLI_DEBUG && echo "++> options -> sso -> mfa"
+          [[ ${DOCLI_DEBUG:-false} == true ]] && echo "++> options -> sso -> mfa"
           check_file_age
           sso_login_mfa
           return 0
         # Error if empty
         elif [[ -z $docli_option ]]; then
-          eval $DOCLI_DEBUG && echo "++> options -> sso -> ERROR(exception)"
+          [[ ${DOCLI_DEBUG:-false} == true ]] && echo "++> options -> sso -> ERROR(exception)"
           echo "** SSO ERROR: No options provided **"
           sso_print_usage
           exit 1
diff --git a/.devops/functions/bash_git_private_dir b/.devops/functions/bash_git_private_dir
--- a/.devops/functions/bash_git_private_dir
+++ b/.devops/functions/bash_git_private_dir
@@ -1,20 +1,34 @@
+#!/usr/bin/env bash
+# [[ ${DOCLI_DEBUG:-false} == true ]]       && set -exo pipefail || set -eo pipefail
+# [[ ${DOCLI_UNSET_VARS:-false} == true ]]  && set -u
+############################################################################### #dltbr
+#              https://DevOps.click - DevOps taken seriously                  # #dltbr
+###############################################################################
+
 ## DOCLI MODULE INFORMATION
 DOCLI_MODULE=bash_git_private_dir
 DOCLI_MODULE_TYPE=functions
-DOCLI_MODULE_VERSION=0.2
+DOCLI_MODULE_VERSION=0.0.01
 DOCLI_MODULE_UPPER=$(echo "$DOCLI_MODULE" | tr '[:lower:]' '[:upper:]')
 
-echo -e "\n***** $DOCLI_MODULE version $DOCLI_MODULE_VERSION ($DOCLI_MODULE_TYPE) *****\n"
+## DEBUG INFORMATION
+[[ ${DOCLI_DEBUG:-false} == true ]] && echo -e "\n***** $DOCLI_MODULE version $DOCLI_MODULE_VERSION ($DOCLI_MODULE_TYPE) *****\n"
+
+# Prevents script from being called directly
+if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
+  echo "* $DOCLI_MODULE: This module cannot be called directly! Exiting... *"
+  exit 1
+fi
 
 create_git_private_dir() {
-    # Check if private dir exists
-    git_private_dir=$DOCLI_PROJECT_ROOT/private
+  # Check if private dir exists
+  git_private_dir=$DOCLI_PROJECT_ROOT/private
 
-    if [ ! -d "$git_private_dir" ]; then
-        echo "Private Directory does not exist. Creating $git_private_dir..."
-        mkdir -p "$git_private_dir"
-        echo "** INFO: Directory $git_private_dir created."
-    else
-        echo "** INFO: Directory $git_private_dir already exists. Skipping..."
-    fi
+  if [ ! -d "$git_private_dir" ]; then
+    echo "Private Directory does not exist. Creating $git_private_dir..."
+    mkdir -p "$git_private_dir"
+    echo "** INFO: Directory $git_private_dir created."
+  else
+    echo "** INFO: Directory $git_private_dir already exists. Skipping..."
+  fi
 }
diff --git a/.devops/functions/bash_gpg_key b/.devops/functions/bash_gpg_key
--- a/.devops/functions/bash_gpg_key
+++ b/.devops/functions/bash_gpg_key
@@ -1,4 +1,9 @@
-#!/bin/bash
+#!/usr/bin/env bash
+# [[ ${DOCLI_DEBUG:-false} == true ]]       && set -exo pipefail || set -eo pipefail
+# [[ ${DOCLI_UNSET_VARS:-false} == true ]]  && set -u
+############################################################################### #dltbr
+#              https://DevOps.click - DevOps taken seriously                  # #dltbr
+###############################################################################
 # gpg -K to list all keys
 ### running "any gpg command" will create:
 # /Users/$USER/.gnupg
@@ -7,13 +12,19 @@
 ## DOCLI MODULE INFORMATION
 DOCLI_MODULE=bash_gpg_key
 DOCLI_MODULE_TYPE=functions
-DOCLI_MODULE_VERSION=0.2
+DOCLI_MODULE_VERSION=0.0.01
 DOCLI_MODULE_UPPER=$(echo "$DOCLI_MODULE" | tr '[:lower:]' '[:upper:]')
 
-echo -e "\n***** $DOCLI_MODULE version $DOCLI_MODULE_VERSION ($DOCLI_MODULE_TYPE) *****\n"
+## DEBUG INFORMATION
+[[ ${DOCLI_DEBUG:-false} == true ]] && echo -e "\n***** $DOCLI_MODULE version $DOCLI_MODULE_VERSION ($DOCLI_MODULE_TYPE) *****\n"
 
-PATH="$DOCLI_DIR/bin:$PATH"
-[[ -d /opt/homebrew/bin ]] && PATH="/opt/homebrew/bin:$PATH" || echo >/dev/null
+# Prevents script from being called directly
+if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
+  echo "* $DOCLI_MODULE: This module cannot be called directly! Exiting... *"
+  exit 1
+fi
+
+PATH="${DOCLI_DIR:-/opt/devops}/bin:/opt/homebrew/bin:/usr/sbin:/sbin:/usr/bin:/bin:/usr/local/bin:/usr/local/sbin:$HOME/devops/bin:$PATH"
 
 #:: ### This part of the code check for the existence of private dir to be used on imports
 #:: - If directory does not exist, it will be created.
diff --git a/.devops/functions/bash_op b/.devops/functions/bash_op
--- a/.devops/functions/bash_op
+++ b/.devops/functions/bash_op
@@ -1,5 +1,6 @@
 #!/usr/bin/env bash
-set -euo pipefail
+# [[ ${DOCLI_DEBUG:-false} == true ]]       && set -exo pipefail || set -eo pipefail
+# [[ ${DOCLI_UNSET_VARS:-false} == true ]]  && set -u
 ############################################################################### #dltbr
 #              https://DevOps.click - DevOps taken seriously                  # #dltbr
 ###############################################################################
@@ -9,7 +10,7 @@ set -euo pipefail
 ## DOCLI MODULE INFORMATION
 DOCLI_MODULE=bash_op
 DOCLI_MODULE_TYPE=functions
-DOCLI_MODULE_VERSION=0.4
+DOCLI_MODULE_VERSION=0.0.01
 DOCLI_MODULE_UPPER=$(echo "$DOCLI_MODULE" | tr '[:lower:]' '[:upper:]')
 
 # Prevents script from being called directly
@@ -18,7 +19,8 @@ if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
   exit 1
 fi
 
-echo -e "\n***** $DOCLI_MODULE version $DOCLI_MODULE_VERSION ($DOCLI_MODULE_TYPE) *****\n"
+## DEBUG INFORMATION
+[[ ${DOCLI_DEBUG:-false} == true ]] && echo -e "\n***** $DOCLI_MODULE version $DOCLI_MODULE_VERSION ($DOCLI_MODULE_TYPE) *****\n"
 
 bash_op_file_name="$(basename "$0")"
 bash_op_file_name_upper=$(basename "$0" | tr '[:lower:]' '[:upper:]')
@@ -40,177 +42,177 @@ fi
 # ONEPASSWORD_URL=<company>.1password.com # Got From .docli_envs
 
 op_print_usage() {
-    echo
-    banner
-    echo "Usage: op (arguments) [OPTIONS]"
-    echo
-    echo "op create document        -> Cleans all AWS SSO Tokens (CLI and SSO caches)"
-    echo "op create item            -> Cleans all AWS SSO Tokens (CLI and SSO caches)"
-    echo "op signout                -> Sign out from all current sessions"
-    echo
-    print_options
-    exit 1
+  echo
+  banner
+  echo "Usage: op (arguments) [OPTIONS]"
+  echo
+  echo "op create document        -> Cleans all AWS SSO Tokens (CLI and SSO caches)"
+  echo "op create item            -> Cleans all AWS SSO Tokens (CLI and SSO caches)"
+  echo "op signout                -> Sign out from all current sessions"
+  echo
+  print_options
+  exit 1
 }
 
 op_check_connection() {
-    # Login to 1Password if not before start
-    check_op_con=$(op account get 2>&1 | tee /tmp/op_con.log || echo "failure" )
-    echo $check_op_con
-    if [[ $check_op_con == *"You are not currently signed in"* ]]; then
-        echo -e "\n**** 1Password CHECK: not_signed_in ;( >> Please enter your 1Password account password! << ****"
-        eval $(op signin --account $ONEPASSWORD_URL)
-    else
-        echo -e "** 1Password CHECK: already logged in ;)\n"
-    fi
+  # Login to 1Password if not before start
+  check_op_con=$(op account get 2>&1 | tee /tmp/op_con.log || echo "failure" )
+  echo $check_op_con
+  if [[ $check_op_con == *"You are not currently signed in"* ]]; then
+    echo -e "\n**** 1Password CHECK: not_signed_in ;( >> Please enter your 1Password account password! << ****"
+    eval $(op signin --account $ONEPASSWORD_URL)
+  else
+    echo -e "** 1Password CHECK: already logged in ;)\n"
+  fi
 }
 
 op_check_requirement() {
-    # Check OnePassword Requirement
-    echo -e "\n${TEXT_MAGENTA} Checking 1 Password requirement"
-    if contains "$DOCLI_PARAM_CLOUD" "${ONEPASSWORD_REQUIRED[@]}"; then
-        echo -e "==== 1Password Required ====\n ${END}"
-        op_check_connection
-    fi
+  # Check OnePassword Requirement
+  echo -e "\n${TEXT_MAGENTA} Checking 1 Password requirement"
+  if contains "$DOCLI_PARAM_CLOUD" "${ONEPASSWORD_REQUIRED[@]}"; then
+    echo -e "==== 1Password Required ====\n ${END}"
+    op_check_connection
+  fi
 }
 
 #:: ## Check if document exists and returns empty or notempty
 op_check_document() {
-    local file_name=$1
-    local file_vault=$2
-    local file_output="${3:-}"
-    check_doc=$(op document list | grep -i $file_name | awk '{ print $2 }' || echo "empty")
-    if [[ $check_doc == "empty" ]]; then
-        op_check_document_result="empty"
-    else
-        op_check_document_result="notempty"
-    fi
+  local file_name=$1
+  local file_vault=$2
+  local file_output="${3:-}"
+  check_doc=$(op document list | grep -i $file_name | awk '{ print $2 }' || echo "empty")
+  if [[ $check_doc == "empty" ]]; then
+    op_check_document_result="empty"
+  else
+    op_check_document_result="notempty"
+  fi
 }
 
 op_get_document() {
-    # Get a document from 1Password
-    local item_name=$1
-    local file_vault=$2
-    local file_output=$3
-    op document get $item_name --vault "$file_vault" --out-file "$file_output"
+  # Get a document from 1Password
+  local item_name=$1
+  local file_vault=$2
+  local file_output=$3
+  op document get $item_name --vault "$file_vault" --out-file "$file_output"
 }
 
 op_create_document() {
-    # Create a document from 1Password
-    local item_name=$1
-    local file_source=$2
-    local file_name=$3
-    local file_vault=$4
-    local tags=$5
-    echo "** Creating $item_name on 1Password..."
-    op_check_document $item_name $file_vault
-    if [[ $op_check_document_result == "empty" ]]; then
-        op document create $file_source --title $item_name --vault "$file_vault" --file-name $file_name --tags $tags
-    else
-        echo "** Document already exists. You must use update or delete. **"
-    fi
+  # Create a document from 1Password
+  local item_name=$1
+  local file_source=$2
+  local file_name=$3
+  local file_vault=$4
+  local tags=$5
+  echo "** Creating $item_name on 1Password..."
+  op_check_document $item_name $file_vault
+  if [[ $op_check_document_result == "empty" ]]; then
+    op document create $file_source --title $item_name --vault "$file_vault" --file-name $file_name --tags $tags
+  else
+    echo "** Document already exists. You must use update or delete. **"
+  fi
 }
 
 op_update_document() {
-    # Update a document from 1Password
-    local item_name=$1
-    local file_source=$2
-    local file_name=$3
-    local file_vault=$4
-    local tags="${5:-}"
-    echo "** Updating $item_name on 1Password..."
-    op_check_document $item_name $file_vault
-    if [[ $op_check_document_result == "notempty" ]]; then
-        if [[ -z $tags ]]; then
-            op document edit $item_name $file_source --vault $file_vault --file-name $file_name && echo "** Update succeeded!" || echo "** Update FAILED try again!"
-        else
-            op document edit $item_name $file_source --vault $file_vault --file-name $file_name --tags $tags && echo "** Update succeeded!" || echo "** Update FAILED try again!"
-        fi
+  # Update a document from 1Password
+  local item_name=$1
+  local file_source=$2
+  local file_name=$3
+  local file_vault=$4
+  local tags="${5:-}"
+  echo "** Updating $item_name on 1Password..."
+  op_check_document $item_name $file_vault
+  if [[ $op_check_document_result == "notempty" ]]; then
+    if [[ -z $tags ]]; then
+      op document edit $item_name $file_source --vault $file_vault --file-name $file_name && echo "** Update succeeded!" || echo "** Update FAILED try again!"
     else
-        echo "** Document does not exist. You must create it before trying to update. **"
+      op document edit $item_name $file_source --vault $file_vault --file-name $file_name --tags $tags && echo "** Update succeeded!" || echo "** Update FAILED try again!"
     fi
+  else
+    echo "** Document does not exist. You must create it before trying to update. **"
+  fi
 }
 
 op_update_document_fields() {
-    # Update a document from 1Password
-    local item_name=$1
-    local file_source=$2
-    local file_name=$3
-    local file_vault=$4
-    local tags=$5
-    local section=$6
-    echo "** Updating $item_name on 1Password..."
-    op_check_document $item_name $file_vault
-    if [[ $op_check_document_result == "notempty" ]]; then
-        op item edit $item_name "$section.$file_name[file]=${file_source}" --vault $file_vault --tags $tags && echo "** Update succeeded!" || echo "** Update FAILED try again!"
-    else
-        echo "** Document does not exist. You must create it before trying to update. **"
-    fi
+  # Update a document from 1Password
+  local item_name=$1
+  local file_source=$2
+  local file_name=$3
+  local file_vault=$4
+  local tags=$5
+  local section=$6
+  echo "** Updating $item_name on 1Password..."
+  op_check_document $item_name $file_vault
+  if [[ $op_check_document_result == "notempty" ]]; then
+    op item edit $item_name "$section.$file_name[file]=${file_source}" --vault $file_vault --tags $tags && echo "** Update succeeded!" || echo "** Update FAILED try again!"
+  else
+    echo "** Document does not exist. You must create it before trying to update. **"
+  fi
 }
 
 op_get_item() {
-    # Get a item from 1Password
-    local item_name=$1
-    local file_vault=$2
-    local fields=$3
-    local file_output="${4:-}"
-    if [[ -z $file_output ]]; then
-        op item get $item_name --vault $file_vault --fields $fields
-    else
-        op item get $item_name --vault $file_vault --fields $fields --out-file $file_output
-    fi
+  # Get a item from 1Password
+  local item_name=$1
+  local file_vault=$2
+  local fields=$3
+  local file_output="${4:-}"
+  if [[ -z $file_output ]]; then
+    op item get $item_name --vault $file_vault --fields $fields
+  else
+    op item get $item_name --vault $file_vault --fields $fields --out-file $file_output
+  fi
 }
 
 op_create_item() {
-    # Create a item from 1Password
-    local item_name=$1
-    local file_source=$2
-    local file_name=$3
-    local file_vault=$4
-    local tags=$5
-    echo "** Creating $item_name on 1Password..."
-    op item create $file_source --title $item_name --vault "$file_vault" --file-name $file_name --tags $tags
+  # Create a item from 1Password
+  local item_name=$1
+  local file_source=$2
+  local file_name=$3
+  local file_vault=$4
+  local tags=$5
+  echo "** Creating $item_name on 1Password..."
+  op item create $file_source --title $item_name --vault "$file_vault" --file-name $file_name --tags $tags
 }
 
 op_create_ca_item() {
-    # Create a item from 1Password
-    local item_name=$1
-    local file_source=$2
-    local file_vault=$3
-    local tags=$4
-    echo "** Creating $item_name on 1Password..."
-    # op item create $file_source --title $item_name --vault "$file_vault" --file-name $file_name --tags $tags
-    op item create --category login --title $item_name --vault "$file_vault" --tags $tags \
-    --url=https://notused.com/ --generate-password=20,letters,digits \
-    username="no-user_ca-file" \
-    "Used By[text]=$item_name" \
-    "Create Command [text]=ops-config/tools/generate-ss-ca/run $short_region $environment" \
-    "p12.$item_name\.p12[file]=${file_source}/$item_name.p12" \
-    "key.$item_name\.key[file]=${file_source}/$item_name.key" \
-    "crt.$item_name\.crt[file]=${file_source}/$item_name.crt"
+  # Create a item from 1Password
+  local item_name=$1
+  local file_source=$2
+  local file_vault=$3
+  local tags=$4
+  echo "** Creating $item_name on 1Password..."
+  # op item create $file_source --title $item_name --vault "$file_vault" --file-name $file_name --tags $tags
+  op item create --category login --title $item_name --vault "$file_vault" --tags $tags \
+  --url=https://notused.com/ --generate-password=20,letters,digits \
+  username="no-user_ca-file" \
+  "Used By[text]=$item_name" \
+  "Create Command [text]=ops-config/tools/generate-ss-ca/run $short_region $environment" \
+  "p12.$item_name\.p12[file]=${file_source}/$item_name.p12" \
+  "key.$item_name\.key[file]=${file_source}/$item_name.key" \
+  "crt.$item_name\.crt[file]=${file_source}/$item_name.crt"
 }
 
 op_update_ca_items() {
-    # Update a document from 1Password
-    local item_name=$1
-    local file_source=$2
-    local file_vault=$3
-    local tags=$4
-    echo "** Updating $item_name on 1Password..."
-    op item edit $item_name --vault "$file_vault" --tags $tags \
-    "Used By[text]=$item_name" \
-    "Create Command [text]=ops-config/tools/generate-ss-ca/run $short_region $environment" \
-    "p12.$item_name\.p12[file]=${file_source}/$item_name.p12" \
-    "key.$item_name\.key[file]=${file_source}/$item_name.key" \
-    "crt.$item_name\.crt[file]=${file_source}/$item_name.crt" || echo "** Update FAILED try again!"
+  # Update a document from 1Password
+  local item_name=$1
+  local file_source=$2
+  local file_vault=$3
+  local tags=$4
+  echo "** Updating $item_name on 1Password..."
+  op item edit $item_name --vault "$file_vault" --tags $tags \
+  "Used By[text]=$item_name" \
+  "Create Command [text]=ops-config/tools/generate-ss-ca/run $short_region $environment" \
+  "p12.$item_name\.p12[file]=${file_source}/$item_name.p12" \
+  "key.$item_name\.key[file]=${file_source}/$item_name.key" \
+  "crt.$item_name\.crt[file]=${file_source}/$item_name.crt" || echo "** Update FAILED try again!"
 }
 
 # op_update_item() {
-#     # Update a item from 1Password
-#     local item_name=$1
-#     local file_source=$2
-#     local file_name=$3
-#     local file_vault=$4
-#     local tags=$5
-#     echo "** Updating $item_name on 1Password..."
-#     op document edit $item_name $file_source --vault $file_vault --file-name $file_name --tags $tags && echo "** Update succeeded!" || echo "** Update FAILED try again!"
+#   # Update a item from 1Password
+#   local item_name=$1
+#   local file_source=$2
+#   local file_name=$3
+#   local file_vault=$4
+#   local tags=$5
+#   echo "** Updating $item_name on 1Password..."
+#   op document edit $item_name $file_source --vault $file_vault --file-name $file_name --tags $tags && echo "** Update succeeded!" || echo "** Update FAILED try again!"
 # }
diff --git a/.devops/functions/bash_os_check b/.devops/functions/bash_os_check
--- a/.devops/functions/bash_os_check
+++ b/.devops/functions/bash_os_check
@@ -1,29 +1,43 @@
+#!/usr/bin/env bash
+# [[ ${DOCLI_DEBUG:-false} == true ]]       && set -exo pipefail || set -eo pipefail
+# [[ ${DOCLI_UNSET_VARS:-false} == true ]]  && set -u
+############################################################################### #dltbr
+#              https://DevOps.click - DevOps taken seriously                  # #dltbr
+###############################################################################
+
 ## DOCLI MODULE INFORMATION
 DOCLI_MODULE=bash_os_check
 DOCLI_MODULE_TYPE=functions
-DOCLI_MODULE_VERSION=0.1
+DOCLI_MODULE_VERSION=0.0.01
 DOCLI_MODULE_UPPER=$(echo "$DOCLI_MODULE" | tr '[:lower:]' '[:upper:]')
 
-echo -e "\n***** $DOCLI_MODULE version $DOCLI_MODULE_VERSION ($DOCLI_MODULE_TYPE) *****\n"
+# Prevents script from being called directly
+if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
+  echo "* $DOCLI_MODULE: This module cannot be called directly! Exiting... *"
+  exit 1
+fi
+
+## DEBUG INFORMATION
+[[ ${DOCLI_DEBUG:-false} == true ]] && echo -e "\n***** $DOCLI_MODULE version $DOCLI_MODULE_VERSION ($DOCLI_MODULE_TYPE) *****\n"
 
 os_check_macos_or_linux() {
-    # Check if the script is running on macOS or Linux
-    OS=$(uname)
-    if [ "$OS" != "Darwin" ] && [ "$OS" != "Linux" ]; then
-        echo "Error: This script only supports macOS and Linux."
-        exit 1
-    fi
+  # Check if the script is running on macOS or Linux
+  OS=$(uname)
+  if [ "$OS" != "Darwin" ] && [ "$OS" != "Linux" ]; then
+    echo "Error: This script only supports macOS and Linux."
+    exit 1
+  fi
 }
 
 # Check if the script is running on macOS or Linux and fill variable $os
 check_os() {
-    os_var=$(uname)
-    if [ "$os_var" == "Darwin" ]; then
-        export os="macos"
-    elif [ "$os_var" == "Linux" ]; then
-        export os="linux"
-    else
-        echo "** ERROR: Supported only by MacOS and Linux. **"
-        return 0
-    fi
+  os_var=$(uname)
+  if [ "$os_var" == "Darwin" ]; then
+    export os="macos"
+  elif [ "$os_var" == "Linux" ]; then
+    export os="linux"
+  else
+    echo "** ERROR: Supported only by MacOS and Linux. **"
+    return 0
+  fi
 }
diff --git a/.devops/tools/ca-generator/client-certificates/run b/.devops/tools/ca-generator/client-certificates/run
--- a/.devops/tools/ca-generator/client-certificates/run
+++ b/.devops/tools/ca-generator/client-certificates/run
@@ -1,7 +1,18 @@
-#!/bin/bash
-set -euo pipefail
+#!/usr/bin/env bash
+[[ ${DOCLI_DEBUG:-false} == true ]]       && set -exo pipefail || set -eo pipefail
+[[ ${DOCLI_UNSET_VARS:-false} == true ]]  && set -u
 
 source $DOCLI_PROJECT_ROOT/.docli_envs
+
+## Override variables with command line arguments
+DOCLI_OWN_NAME=${1:-$DOCLI_OWN_NAME}
+DOCLI_OWN_EMAIL=${2:-$DOCLI_OWN_EMAIL}
+
+# Check if certificate will be imported to firefox
+DOCLI_CERT_IMPORT_TO_FIREFOX=${DOCLI_CERT_IMPORT_TO_FIREFOX:-false}
+
+# Check if certificate will be CRL disabled
+DOCLI_CLIENT_CERT_CRL_DISABLED=${DOCLI_CLIENT_CERT_CRL_DISABLED:-false}
 
 # Check for existence of DOCLI_OWN_NAME and DOCLI_OWN_EMAIL variables
 if [[ -z "$DOCLI_OWN_NAME" ]]; then
@@ -19,48 +30,105 @@ fi
 # Remove @domain from e-mails
 user_name="${user_email%%@*}"
 
-# mkdir -p $DOCLI/CA/clientsROOT
-mkdir -p $DOCLI/CA/clientsINTERMEDIATE
-
-# client_root_dir="$DOCLI/CA/clientsROOT"
+client_root_dir="$DOCLI/CA/clientsINTERMEDIATE" # $DOCLI/CA/clientsROOT
 client_root_dir="$DOCLI/CA/clientsINTERMEDIATE"
 timestamp=$(date +%s)
 current_date=$(date)
-client_cert_user=$(whoami)
-consul_server="consul-server-$DOCLI_PROJECT_ENTERPRISE_DC_NAME.$DOCLI_ENTERPRISE_DC_SRG.$DOCLI_ENTERPRISE_DC_ENV.$SSL_PRODUCT_DOMAIN"
+os_user=$(whoami)
+cert_check_url=${DOCLI_CERT_CHECK_URL:-"https://noserver.local"}
 
+## Create Client Root Directory
+[[ ! -d $client_root_dir ]] && mkdir -p $client_root_dir
+
+## Client Certificate LOG GENERATION
 [[ ! -f $client_root_dir/gen_client_cert.log ]] && touch $client_root_dir/gen_client_cert.log
-echo "" >> $client_root_dir/gen_client_cert.log
-echo "#------------------- $current_date -------------------#" >> $client_root_dir/gen_client_cert.log
-echo "** Certification Generation Log **" >> $client_root_dir/gen_client_cert.log
-echo "timestamp:        $timestamp" >> $client_root_dir/gen_client_cert.log
-echo "client_cert_user: $client_cert_user" >> $client_root_dir/gen_client_cert.log
+log_section=$(cat <<EOF
+$current_date:
+** Certification Generation Log **
+timestamp: \`$timestamp\`
+os_user:   \`$os_user\`
+#------------------- Certficate Information -------------------#
+User:  \`$user_name\`
+Email: \`$user_email\`
+EOF
+)
+echo "$log_section" >> $client_root_dir/gen_client_cert.log
 
-echo "Client Certificate: Generates Client Private Key"
+echo -e "\n** SSL Client Certificate: Generates Client Private Key **"
 [[ ! -f $client_root_dir/$user_name.key ]] && /usr/bin/openssl genpkey -algorithm RSA -out $client_root_dir/$user_name.key
 
-echo "Client Certificate: Create a certificate signing request (CSR) for the client key: [ENTERPRISE]"
-/usr/bin/openssl req -new -key $client_root_dir/$user_name.key -out $client_root_dir/$user_name.csr -subj "/C=$SSL_COUNTRY/ST=$SSL_STATE/L=$SSL_LOCALITY/O=$SSL_COMPANY/OU=$SSL_OU/OU=ent/CN=$full_name ($user_email)"
+### TEMPLATEFILE
+echo -e "\n** SSL Client Certificate: Generates Template File (openssl.cnf)[current directory] **"
+cat <<EOFtemplate > openssl.cnf
+[ req ]
+default_bits            = 2048
+default_md              = sha256
+prompt                  = no
+encrypt_key             = no
+distinguished_name      = req_distinguished_name
+req_extensions          = req_ext
 
-echo "Client Certificate: Sign the CSR with the CA:"
-/usr/bin/openssl x509 -req -in $client_root_dir/$user_name.csr -CA $DOCLI/CA/intermediateCA/certs/intermediate.ent.cert.pem -CAkey $DOCLI/CA/intermediateCA/private/intermediate.ent.key.pem -CAcreateserial -out $client_root_dir/$user_name.crt -days 1825
+[ req_distinguished_name ]
+countryName             = $SSL_COUNTRY
+localityName            = $SSL_LOCALITY
+stateOrProvinceName     = $SSL_STATE
+organizationName        = $SSL_COMPANY
+organizationalUnitName  = $SSL_OU
+commonName              = $full_name ($user_email)
+emailAddress            = $user_email
+
+[ req_ext ]
+extendedKeyUsage = clientAuth
+crlDistributionPoints = URI:${DOCLI_CERT_CRL_URL}
+
+[ req_distinguished_name ]
+EOFtemplate
+
+echo -e "\n** SSL Client Certificate: Applying template variable substitution **"
+envsubst < openssl.cnf > cert-req.cnf
+
+echo -e "\n** SSL Client Certificate: Create a certificate signing request (CSR) for the client key: [ENTERPRISE] **"
+/usr/bin/openssl req -new -key $client_root_dir/$user_name.key -out $client_root_dir/$user_name.csr -config cert-req.cnf
+
+if [[ $DOCLI_CLIENT_CERT_CRL_DISABLED == false ]]; then
+  echo -e "\n** SSL Client Certificate: Sign the CSR with the CA using CRL **""
+  /usr/bin/openssl x509 -req -in $client_root_dir/$user_name.csr -CA $DOCLI/CA/intermediateCA/certs/intermediate.ent.cert.pem -CAkey $DOCLI/CA/intermediateCA/private/intermediate.ent.key.pem -CAcreateserial -out $client_root_dir/$user_name.crt -days $DOCLI_CERT_EXPIRY -extfile cert-req.cnf -extensions req_ext
+else
+  echo -e "\n** SSL Client Certificate: Sign the CSR with the CA NOT using CRL **""
+  /usr/bin/openssl x509 -req -in $client_root_dir/$user_name.csr -CA $DOCLI/CA/intermediateCA/certs/intermediate.ent.cert.pem -CAkey $DOCLI/CA/intermediateCA/private/intermediate.ent.key.pem -CAcreateserial -out $client_root_dir/$user_name.crt -days $DOCLI_CERT_EXPIRY
+fi
+
+echo -e "\n* Removing Temporary Template File *"
+rm cert-req.cnf
+
+# ## OLD METHOD - WITHOUT CRL and not using TEMPLATE FILE
+# echo "Client Certificate: Create a certificate signing request (CSR) for the client key: [ENTERPRISE]"
+# /usr/bin/openssl req -new -key $client_root_dir/$user_name.key -out $client_root_dir/$user_name.csr -subj "/C=$SSL_COUNTRY/ST=$SSL_STATE/L=$SSL_LOCALITY/O=$SSL_COMPANY/OU=$SSL_OU/OU=ent/CN=$full_name ($user_email)"
+
+# echo "Client Certificate: Sign the CSR with the CA:"
+# /usr/bin/openssl x509 -req -in $client_root_dir/$user_name.csr -CA $DOCLI/CA/intermediateCA/certs/intermediate.ent.cert.pem -CAkey $DOCLI/CA/intermediateCA/private/intermediate.ent.key.pem -CAcreateserial -out $client_root_dir/$user_name.crt -days $DOCLI_CERT_EXPIRY
 # /usr/bin/openssl x509 -req -in $client_root_dir/$user_name.csr -CA $DOCLI/CA/rootCA/certs/ca.cert.pem -CAkey $DOCLI/CA/rootCA/private/ca.key.pem -CAcreateserial -out $client_root_dir/$user_name.crt -days 1825
 # /usr/bin/openssl x509 -req -in $client_root_dir/$user_name.csr -CA $DOCLI/CA/intermediateCA/certs/ca-chain-cert.pem -CAkey $DOCLI/CA/rootCA/private/ca.key.pem -CAcreateserial -out $client_root_dir/$user_name.crt -days 1825
 
-# MACOS ONLY
-# Find and delete the associated key
-# key_hash=$(security find-key -c "$full_name ($user_email)" ~/Library/Keychains/login.keychain-db | awk '/keychain:/{print $4}')
-# if [ ! -z "$key_hash" ]; then
-#   sudo security delete-key -Z "$key_hash" ~/Library/Keychains/login.keychain-db
-# fi
+# # MACOS ONLY
+# # Find and delete the associated key
+# # key_hash=$(security find-key -c "$full_name ($user_email)" ~/Library/Keychains/login.keychain-db | awk '/keychain:/{print $4}')
+# # if [ ! -z "$key_hash" ]; then
+# #   sudo security delete-key -Z "$key_hash" ~/Library/Keychains/login.keychain-db
+# # fi
+#
+# # # Find and delete associated keys
+# # security find-key -c "$full_name ($user_email)" ~/Library/Keychains/login.keychain-db | awk '/keychain:/{print $4}' | while read -r key_hash; do
+# #   if [ ! -z "$key_hash" ]; then
+# #     echo "* Deleting Key from Hash: $key_hash *"
+# #     sudo security delete-key -Z "$key_hash" ~/Library/Keychains/login.keychain-db || echo "* ERROR: Could not delete private key (hash: $key_hash) *"
+# #   fi
+# # done
+# # fi
 
-# # Find and delete associated keys
-# security find-key -c "$full_name ($user_email)" ~/Library/Keychains/login.keychain-db | awk '/keychain:/{print $4}' | while read -r key_hash; do
-#   if [ ! -z "$key_hash" ]; then
-#     echo "* Deleting Key from Hash: $key_hash *"
-#     sudo security delete-key -Z "$key_hash" ~/Library/Keychains/login.keychain-db || echo "* ERROR: Could not delete private key (hash: $key_hash) *"
-#   fi
-# done
+#######################################################################################################################################################
+# OS AND BROWSER CERTIFICATE IMPORT
+#######################################################################################################################################################
 
 ############# CLEANUP #############
 # Delete the certificate AND private key (Adding -Z path does not work)
@@ -90,23 +158,29 @@ ls -larth $client_root_dir
 echo
 
 ## FIREFOX
-# Find Firefox profiles and import the certificate
-while read -r profile; do
-  # Clean actual Firefox certificates
-  echo "* Own Client Certificate -> Removing $client_root_dir/$user_name.crt from Firefox Profiles *"
-  certutil -D -n "$full_name ($user_email)" -d "sql:$profile" || echo "* $full_name ($user_email) does not exist *"
+if [[ $DOCLI_CERT_IMPORT_TO_FIREFOX == "true" ]]; then
+  # Find Firefox profiles and import the certificate
+  while read -r profile; do
+    # Clean actual Firefox certificates
+    echo "* Own Client Certificate -> Removing $client_root_dir/$user_name.crt from Firefox Profiles *"
+    certutil -D -n "$full_name ($user_email)" -d "sql:$profile" || echo "* $full_name ($user_email) does not exist *"
 
-  # Import PCKS12
-  echo "Importing certificate into Firefox profile in directory: $profile"
-  pk12util -i $client_root_dir/$user_name.p12 -d "$profile" -W ''
+    # Import PCKS12
+    echo "Importing certificate into Firefox profile in directory: $profile"
+    pk12util -i $client_root_dir/$user_name.p12 -d "$profile" -W ''
 
-  # List if all Keys were cleaned
-  echo -e "\n======================================================================================"
-  echo -e "*                          LISTING ALL FIREFOX CERTIFICATES                          *"
-  echo -e "======================================================================================"
-  certutil -L -d "sql:$profile"
-  echo -e "\n======================================================================================\n"
-done < <(find $HOME/.mozilla/firefox/ $HOME/.mozilla/firefox/*/ "$HOME/Library/Application Support/Firefox/Profiles" -maxdepth 1 -name '*.default*' -type d)
+    # List if all Keys were cleaned
+    echo -e "\n======================================================================================"
+    echo -e "*                          LISTING ALL FIREFOX CERTIFICATES                          *"
+    echo -e "======================================================================================"
+    certutil -L -d "sql:$profile"
+    echo -e "\n======================================================================================\n"
+  done < <(find $HOME/.mozilla/firefox/ $HOME/.mozilla/firefox/*/ "$HOME/Library/Application Support/Firefox/Profiles" -maxdepth 1 -name '*.default*' -type d)
+fi
+
+#######################################################################################################################################################
+# CERTIFICATE VALIDATION
+#######################################################################################################################################################
 
 ###################################
 #### Mutual TLS Authentication ####
@@ -116,12 +190,25 @@ done < <(find $HOME/.mozilla/firefox/ $HOME/.mozilla/firefox/*/ "$HOME/Library/A
 # If you're trying to access the Consul UI, some browsers like Chrome and Safari will automatically prompt you to choose a client certificate for mutual TLS authentication.
 
 # Testing/Using it via curl:
-echo "* TEST: curl using --cacert $DOCLI/CA/intermediateCA/certs/ca-chain-cert.pem *"
-curl --cert $client_root_dir/$user_name.crt --key $client_root_dir/$user_name.key --cacert $DOCLI/CA/intermediateCA/certs/ca-chain-cert.pem https://$consul_server:8501/ui/ || echo "* ERROR: Could not validate certificate using cacert *"
-echo "* TEST: curl using --capath $DOCLI/CA/c_rehash *"
-curl --cert $client_root_dir/$user_name.crt --key $client_root_dir/$user_name.key --capath $DOCLI/CA/c_rehash https://$consul_server:8501/ui/ || echo "* ERROR: Could not validate certificate using capath *"
+echo "** TEST: curl using --cacert $DOCLI/CA/intermediateCA/certs/ca-chain-cert.pem **"
+curl --cert $client_root_dir/$user_name.crt --key $client_root_dir/$user_name.key --cacert $DOCLI/CA/intermediateCA/certs/ca-chain-cert.pem $cert_check_url > cert_chain_test_output.log && echo "* OK: Successfully validated certificate using cacert *" || echo "* ERROR: Could not validate certificate using cacert *"
+echo "** TEST: curl using --capath $DOCLI/CA/c_rehash **"
+curl --cert $client_root_dir/$user_name.crt --key $client_root_dir/$user_name.key --capath $DOCLI/CA/c_rehash $cert_check_url > cert_c_rehashtest_output.log && echo "* OK: Successfully validated certificate using capath *" || echo "* ERROR: Could not validate certificate using capath *"
 
 zip $HOME/Downloads/$user_name.zip $client_root_dir/$user_name.key $client_root_dir/$user_name.crt $client_root_dir/$user_name.p12
 # TODO: do a process to send user zip to devops@domain.com or in a slack channel.
 
 # rm -rf $client_root_dir/*
+
+echo "** Notification: Sending Slack notification **"
+# curl -X POST \
+#   https://slack.com/api/chat.postMessage \
+#   -H 'Content-Type: application/json' \
+#   -d '{"text": "'"${log_section}"'", "channel": "#devops-info"}' \
+#   -H "Authorization: Bearer $SLACK_TOKEN_BOT"
+
+curl -X POST \
+  https://slack.com/api/chat.postMessage \
+  -H 'Content-Type: application/json' \
+  -d "$(jq -n --arg text "$log_section" '{text: $text, channel: "#devops-info"}')" \
+  -H "Authorization: Bearer $SLACK_TOKEN_BOT"
diff --git a/.devops/tools/ca-generator/client-certificates/verify b/.devops/tools/ca-generator/client-certificates/verify
--- a/.devops/tools/ca-generator/client-certificates/verify
+++ b/.devops/tools/ca-generator/client-certificates/verify
@@ -1,7 +1,8 @@
-#!/bin/bash
-set -euo pipefail
+#!/usr/bin/env bash
+[[ ${DOCLI_DEBUG:-false} == true ]]       && set -exo pipefail || set -eo pipefail
+[[ ${DOCLI_UNSET_VARS:-false} == true ]]  && set -u
 
-export PATH="/opt/homebrew/bin:$HOME/devops/bin:$PATH"
+export PATH="${DOCLI_DIR:-/opt/devops}/bin:/opt/homebrew/bin:/usr/sbin:/sbin:/usr/bin:/bin:/usr/local/bin:/usr/local/sbin:$HOME/devops/bin:$PATH"
 
 # Check for existence of docli_full_name and docli_user_email variables
 if [[ -z "$DOCLI_OWN_NAME" ]]; then
@@ -27,7 +28,7 @@ client_root_dir="$DOCLI/CA/clientsROOT"
 timestamp=$(date +%s)
 current_date=$(date)
 client_cert_user=$(whoami)
-consul_server="consul-test.use1.ent.devops.click"
+check_url="${DOCLI_PRIVATE_CA_URL:-localhost}"
 
 ## Mutual TLS Authentication with Consul Server
 
@@ -37,63 +38,24 @@ consul_server="consul-test.use1.ent.devops.click"
 # Testing/Using it via curl:
 echo "Command Line Authentication:"
 
-echo -e "\n** VERIFY SERVER CERTIFICATES **"
-# /opt/homebrew/bin/openssl s_client -showcerts -connect $consul_server:8501/ui/ || echo
-echo -e "\n** VERIFY SERVER CERTIFICATES WITH YOUR KEY/CERT **"
-# /opt/homebrew/bin/openssl s_client -connect $consul_server:8501/ui/ -cert $client_root_dir/$user_name.crt -key $client_root_dir/$user_name.key -CAfile $DOCLI/CA/intermediateCA/certs/ca-chain-cert.pem || echo
+echo -e "\n** VERIFY SERVER CERTIFICATES (Curl HTTP/2) **"
+curl -vvv --http2 --cert new_client_cert.pem --key new_client_key.pem --cacert $DOCLI/CA/intermediateCA/certs/ca-chain-cert.pem https://$check_url || echo
 
-curl -v --http2 --cert $client_root_dir/$user_name.crt --key $client_root_dir/$user_name.key --cacert $DOCLI/CA/intermediateCA/certs/ca-chain-cert.pem https://$consul_server:8501/ui/ || echo
-echo end verbose
-echo end verbose
-echo end verbose
-echo end verbose
-echo end verbose
-echo end verbose
-echo end verbose
-echo end verbose
-echo end verbose
-curl -vvv --http2 --cert new_client_cert.pem --key new_client_key.pem --cacert $DOCLI/CA/intermediateCA/certs/ca-chain-cert.pem https://$consul_server:8501/ui/ || echo
-echo end verbose2
-echo end verbose2
-echo end verbose2
-echo end verbose2
-echo end verbose2
-echo end verbose2
-echo end verbose2
-echo end verbose2
-echo end verbose2
-openssl s_client -connect $consul_server:8501/ui/ -CAfile $DOCLI/CA/intermediateCA/certs/ca-chain-cert.pem -cert new_client_cert.pem -key new_client_key.pem -debug -msg || echo
-echo end verbose3
-echo end verbose3
-echo end verbose3
-echo end verbose3
-echo end verbose3
-echo end verbose3
-echo end verbose3
-echo end verbose3
-echo end verbose3
-/opt/homebrew/bin/openssl s_client -connect $consul_server:8501/ui/ -CAfile $DOCLI/CA/intermediateCA/certs/ca-chain-cert.pem -cert new_client_cert.pem -key new_client_key.pem -debug -msg || echo
-echo end verbose-OPENSSL
-echo end verbose-OPENSSL
-echo end verbose-OPENSSL
-echo end verbose-OPENSSL
-echo end verbose-OPENSSL
-echo end verbose-OPENSSL
-echo end verbose-OPENSSL
-echo end verbose-OPENSSL
-echo end verbose-OPENSSL
-curl --cert $client_root_dir/$user_name.crt --key $client_root_dir/$user_name.key --cacert $DOCLI/CA/intermediateCA/certs/intermediate.ent.cert.pem https://$consul_server:8501/ui/ || echo
+echo -e "\n** VERIFY SERVER CERTIFICATES (OpenSSL) **"
+openssl s_client -connect $check_url -CAfile $DOCLI/CA/intermediateCA/certs/ca-chain-cert.pem -cert new_client_cert.pem -key new_client_key.pem -debug -msg || echo
 
+echo -e "\n** VERIFY SERVER CERTIFICATES WITH YOUR KEY/CERT (Curl) **"
+curl --cert $client_root_dir/$user_name.crt --key $client_root_dir/$user_name.key --cacert $DOCLI/CA/intermediateCA/certs/intermediate.ent.cert.pem https://$check_url || echo
 
 echo -e "\n** VERIFY TCP HANDSHAKES **"
-# sudo tcpdump -i any -s 0 -w output.pcap "port 8501 and host $consul_server"
+# sudo tcpdump -i any -s 0 -w output.pcap "port 8501 and host $check_url"
 
-# curl --cert $client_root_dir/$user_name.crt --key $client_root_dir/$user_name.key --cacert $DOCLI/CA/intermediateCA/certs/intermediate.ent.cert.pem https://$consul_server:8501/ui/ || echo "FAIL WITH CA BUNDLE CERT"
-curl --cert $client_root_dir/$user_name.crt --key $client_root_dir/$user_name.key --cacert $DOCLI/CA/intermediateCA/certs/ca-chain-cert.pem https://$consul_server:8501/ui/ || echo "FAIL WITH CA ENT CERT"
-curl --cert $client_root_dir/$user_name.crt --key $client_root_dir/$user_name.key https://$consul_server:8501/ui/ || echo "FAIL WITH CLIENT CERT ONLY"
+# curl --cert $client_root_dir/$user_name.crt --key $client_root_dir/$user_name.key --cacert $DOCLI/CA/intermediateCA/certs/intermediate.ent.cert.pem https://$check_url || echo "FAIL WITH CA BUNDLE CERT"
+curl --cert $client_root_dir/$user_name.crt --key $client_root_dir/$user_name.key --cacert $DOCLI/CA/intermediateCA/certs/ca-chain-cert.pem https://$check_url || echo "FAIL WITH CA ENT CERT"
+curl --cert $client_root_dir/$user_name.crt --key $client_root_dir/$user_name.key https://$check_url || echo "FAIL WITH CLIENT CERT ONLY"
 
 
-curl --cacert $DOCLI/CA/intermediateCA/certs/ca-chain-cert.pem https://$consul_server:8501/ui/ || echo "FAIL WITH CA ENT CERT ONLY"
-curl --key $client_root_dir/$user_name.key https://$consul_server:8501/ui/ || echo "FAIL WITH CLIENT KEY ONLY"
-curl --cert $client_root_dir/$user_name.crt https://$consul_server:8501/ui/ || echo "FAIL WITH CLIENT CERT ONLY"
-curl --cert $client_root_dir/$user_name.p12 https://$consul_server:8501/ui/ || echo "FAIL WITH CLIENT P12"
+curl --cacert $DOCLI/CA/intermediateCA/certs/ca-chain-cert.pem https://$check_url || echo "FAIL WITH CA ENT CERT ONLY"
+curl --key $client_root_dir/$user_name.key https://$check_url || echo "FAIL WITH CLIENT KEY ONLY"
+curl --cert $client_root_dir/$user_name.crt https://$check_url || echo "FAIL WITH CLIENT CERT ONLY"
+curl --cert $client_root_dir/$user_name.p12 https://$check_url || echo "FAIL WITH CLIENT P12"
