Update runtf
private envs cleanup procedures

diff --git a/.devops/bin/runtf b/.devops/bin/runtf
--- a/.devops/bin/runtf
+++ b/.devops/bin/runtf
@@ -16,7 +16,7 @@ PATH=/usr/sbin:/sbin:/usr/bin:/bin:/usr/local/bin:/usr/local/sbin:/opt/devops/bi
 ## DOCLI MODULE INFORMATION
 DOCLI_MODULE=runtf
 DOCLI_MODULE_TYPE=bin
-DOCLI_MODULE_VERSION=1.13
+DOCLI_MODULE_VERSION=1.14
 DOCLI_MODULE_UPPER=$(echo "$DOCLI_MODULE" | tr '[:lower:]' '[:upper:]')
 
 echo -e "\n***** $DOCLI_MODULE version $DOCLI_MODULE_VERSION ($DOCLI_MODULE_TYPE) *****\n"
@@ -649,41 +649,8 @@ catch() {
   fi
 }
 
-# Remove script created files
-cleanup() {
-  echo -e "${TEXT_MAGENTA}** Cleaning all temporary and sensitive data: begin **${TEXT_BLUE}"
-
-  # Cleanup Terraform Files
-  # rm -rf remote-state.tf .terraform.lock.hcl .terraform terraform.tfstate.d errored.tfstate terraform.tf terraform.tfstate terraform.tfstate.backup
-  # rm -rf remote-state.tf .terraform.lock.hcl
-  # rm -rf .terraform terraform.tfstate.d
-
-  # Cleanup Sensitive information used in client-accounts creation
-  [[ $current_key == "client-accounts" || $current_key == "client-users" || $current_key == "service-users" ]] && cleanup_sensitive
-
-  # Cleanup Terraform secrets-custom.tf file
-  if contains "$current_key" "${CUSTOM_SECRETS[@]}"; then
-    local file_output="$PWD/secrets-custom.tf"
-    [[ -f $file_output ]] && rm $file_output
-  fi
-
-  # Cleanup Terraform .private_envs file
-  if [ -f "$DOCLI_PROJECT_ROOT/terraform/$DOCLI_PARAM_CLOUD/deploy/$current_key/.private_envs" ]; then
-    rm -rf "$DOCLI_PROJECT_ROOT/terraform/$DOCLI_PARAM_CLOUD/deploy/$current_key/.private_envs"
-  fi
-
-  echo -e "${TEXT_MAGENTA}** Cleaning all temporary and sensitive data: begin **${END}"
-}
-
-# Clean up on errors
-cleanup_on_error() {
-  echo -e "${BOLD}${TEXT_RED}* ERROR: Cleaning Terraform temporary and state files and rolling back changes${END}\n"
-
-  cleanup
-  exit 1
-}
-
 # Download and build .private_envs file to be loaded by runtf if needed. (It generates this list only on the existence of .op_load_envs)
+export OP_LOAD_ENVS_DIR="$DOCLI_PROJECT_ROOT/terraform/$DOCLI_PARAM_CLOUD/deploy/$current_key/.private_op_load_envs_dir"
 op_load_envs() {
   echo -e "${BOLD}${TEXT_GREEN}** 1password load envs: begin ${END}\n"
 
@@ -732,7 +699,8 @@ op_load_envs() {
 
     # Create individual files if "RESULT AS FILE = 1"
     if [[ $load_as_file == "1" ]]; then
-      file_path="$DOCLI_PROJECT_ROOT/terraform/$DOCLI_PARAM_CLOUD/deploy/$current_key/private_${op_item_name}.${file_format}"
+      [[ ! -d $OP_LOAD_ENVS_DIR ]] && mkdir -p $OP_LOAD_ENVS_DIR
+      file_path="$OP_LOAD_ENVS_DIR/private_${op_item_name}.${file_format}"
       if [ ! -f "$file_path" ]; then
         touch "$file_path"
       fi
@@ -782,6 +750,45 @@ cleanup_sensitive() {
   fi
 
   echo -e "${BOLD}${TEXT_YELLOW}** Cleaning sensitive information: end ${END}\n"
+}
+
+# Remove script created files
+cleanup() {
+  echo -e "${TEXT_MAGENTA}** Cleaning all temporary and sensitive data: begin **${TEXT_BLUE}"
+
+  # Cleanup Terraform Files
+  # rm -rf remote-state.tf .terraform.lock.hcl .terraform terraform.tfstate.d errored.tfstate terraform.tf terraform.tfstate terraform.tfstate.backup
+  # rm -rf remote-state.tf .terraform.lock.hcl
+  # rm -rf .terraform terraform.tfstate.d
+
+  # Cleanup Sensitive information used in client-accounts creation
+  [[ $current_key == "client-accounts" || $current_key == "client-users" || $current_key == "service-users" ]] && cleanup_sensitive
+
+  # Cleanup Terraform secrets-custom.tf file
+  if contains "$current_key" "${CUSTOM_SECRETS[@]}"; then
+    local file_output="$PWD/secrets-custom.tf"
+    [[ -f $file_output ]] && rm $file_output
+  fi
+
+  # Cleanup Terraform 1Password created .private_envs file
+  if [ -f "$DOCLI_PROJECT_ROOT/terraform/$DOCLI_PARAM_CLOUD/deploy/$current_key/.private_envs" ]; then
+    rm -rf "$DOCLI_PROJECT_ROOT/terraform/$DOCLI_PARAM_CLOUD/deploy/$current_key/.private_envs"
+  fi
+
+  # Cleanup Terraform 1Password created temporary files
+  if [[ -d $OP_LOAD_ENVS_DIR ]]; then
+    rm -rf $OP_LOAD_ENVS_DIR
+  fi
+
+  echo -e "${TEXT_MAGENTA}** Cleaning all temporary and sensitive data: begin **${END}"
+}
+
+# Clean up on errors
+cleanup_on_error() {
+  echo -e "${BOLD}${TEXT_RED}* ERROR: Cleaning Terraform temporary and state files and rolling back changes${END}\n"
+
+  cleanup
+  exit 1
 }
 
 # Check Terraform files for errors
