release/0.0.28

diff --git a/.devops/tools/ca-generator/client-certificates/run b/.devops/tools/ca-generator/client-certificates/run
--- a/.devops/tools/ca-generator/client-certificates/run
+++ b/.devops/tools/ca-generator/client-certificates/run
@@ -9,7 +9,7 @@ DOCLI_OWN_NAME=${1:-$DOCLI_OWN_NAME}
 DOCLI_OWN_EMAIL=${2:-$DOCLI_OWN_EMAIL}
 
 ## Initialize needed variables
-[[ -f ${DOCLI_PROJECT_ROOT:-$HOME/Documents/BitBucket/ops-config}/files/functions/bash_doenv ]] && source ${DOCLI_PROJECT_ROOT:-$HOME/Documents/BitBucket/ops-config}/files/functions/bash_doenv || echo "** ERROR: Could not find bash_doenv script **" && exit 1
+[[ -f ${DOCLI_PROJECT_ROOT:-$HOME/Documents/BitBucket/ops-config}/files/functions/bash_doenv ]] && source ${DOCLI_PROJECT_ROOT:-$HOME/Documents/BitBucket/ops-config}/files/functions/bash_doenv || ( echo "** ERROR: Could not find bash_doenv script **" && exit 1 )
 ## Setting up SLACK
 doenv slack || echo "** WARN: Could not setup slack parameters. Notification will not work **"
 
@@ -39,10 +39,14 @@ cert_check_url=${DOCLI_CERT_CHECK_URL:-"https://noserver.local"}
 ## Create Client Root Directory
 [[ ! -d $use_client_dir ]] && mkdir -p $use_client_dir
 
+echo AHHHHHHHHHHHHHHHHHHHHHH MOTHERRRRRRRRRRRF
+echo AHHHHHHHHHHHHHHHHHHHHHH MOTHERRRRRRRRRRRF
+echo AHHHHHHHHHHHHHHHHHHHHHH MOTHERRRRRRRRRRRF
+
 ## Client Certificate LOG GENERATION
 [[ ! -f $use_client_dir/gen_client_cert.log ]] && touch $use_client_dir/gen_client_cert.log
 log_section=$(cat <<EOF
-:lock: *Private CA - Client Certification Generation Log*
+\:lock\: *Private CA - Client Certification Generation Log*
 \`$current_date\`
 *Requesters Information*
 \`\`\`
@@ -224,7 +228,7 @@ if [[ "${DOCLI_SLACK_NOTIFY:-off}" == "on" ]]; then
   curl -X POST \
     https://slack.com/api/chat.postMessage \
     -H 'Content-Type: application/json' \
-    -d "$(jq -n --arg text "$log_section" "{icon_emoji: "${DOCLI_PRIVATE_CA_SLACK_ICON_EMOJI:-":fire:"}", username: "${DOCLI_PRIVATE_CA_SLACK_USERNAME:-"DevOps.click-Bot"}" , text: $text, channel: "#${DOCLI_PRIVATE_CA_SLACK_CHANNEL:-general}"}")" \
+    -d "$(jq -n --arg text "$log_section" "{\"icon_emoji\":\"${DOCLI_PRIVATE_CA_SLACK_ICON_EMOJI:-':fire:'}\", \"username\":\"${DOCLI_PRIVATE_CA_SLACK_USERNAME:-'DevOps.click-Bot'}\", \"channel\":\"#${DOCLI_PRIVATE_CA_SLACK_CHANNEL:-general}\", \"text\":$text}")" \
     -H "Authorization: Bearer $SLACK_TOKEN_BOT"
 else
   echo "Slack notification disabled"
